#!/usr/bin/bash
clear '=================================================='
echo -e '\e[1;31m' "Author      = BisQuat"
echo -e '\e[1;31m' "Facebook    = Kamal"  
echo -e '\e[1;37m' "Instagram   = Kamal_Stv18 "    
echo -e '\e[1;37m' "\nDate
echo -e '\e[1;36m' '=================================================='
echo -e '\e[1;31m' "[K]Boom SMS & Call"
echo -e '\e[1;31m' "[A]Boom SMS Tsel"
echo -e '\e[1;31m' "[M]............."
echo -e '\e[1;37m' "[A]IPGeolacation"
echo -e '\e[1;37m' "[L]............."
echo -e '\e[1;36m' '=================================================='

read -p " Pilih Salah Satu :" act;
if [ $act = K ]
then
figlet -f slant boom
git clone https://github.com/icha2618/boom
exit
fi
if [ $act = A ]
then
figlet -f slant tsel
echo
git clone https://github.com/icha2618/tsel
exit
fi
if [ $act = M ]
then
figlet -f slant LITESPAM
echo
git clone https://github.com/4L13199/LITESPAM
exit
fi
if [ $act = A ]
then
figlet -f slant IPGeolacation
echo
git clone https://github.com/maldevel/IPGeoLocation.git
exit
fi
if [ $act = L ]
then
figlet -f slant IPGeolacation
echo
git clone https://github.com/maldevel/IPGeoLocation.git
exit
